# Generated by Django 4.1.4 on 2023-08-03 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Userregister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=200)),
                ('number', models.IntegerField()),
                ('address', models.TextField()),
                ('password', models.CharField(max_length=12)),
            ],
        ),
    ]
