# Generated by Django 4.1.4 on 2023-08-03 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregister',
            name='surname',
            field=models.CharField(default=' ', max_length=20),
        ),
        migrations.AlterField(
            model_name='userregister',
            name='address',
            field=models.TextField(max_length=250),
        ),
    ]
