# Generated by Django 4.1.4 on 2023-08-03 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_alter_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Price',
        ),
        migrations.AddField(
            model_name='product',
            name='Pricee',
            field=models.IntegerField(default=0),
        ),
    ]
