# Generated by Django 4.1.4 on 2023-08-03 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_remove_product_price_product_pricee'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ImageFile',
            field=models.ImageField(blank=True, upload_to='product_image'),
        ),
    ]
