# Generated by Django 4.1.4 on 2023-09-04 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_category_imagefile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contactus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=200)),
                ('number', models.IntegerField(max_length=10)),
                ('Message', models.TextField(max_length=250)),
            ],
        ),
    ]
