# Generated by Django 4.1.4 on 2023-09-08 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_contactus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_created=True, auto_now=True)),
                ('userid', models.CharField(max_length=200)),
                ('productid', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('Quantity', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=200)),
                ('paymentmethod', models.CharField(max_length=200)),
                ('transactionid', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('surname', models.CharField(default=' ', max_length=20)),
                ('email', models.EmailField(max_length=200)),
                ('number', models.IntegerField()),
                ('address', models.TextField(max_length=250)),
                ('password', models.CharField(max_length=12)),
            ],
        ),
        migrations.RenameField(
            model_name='contactus',
            old_name='Message',
            new_name='message',
        ),
        migrations.AlterField(
            model_name='contactus',
            name='number',
            field=models.IntegerField(),
        ),
    ]
